"""Client-facing serving gateway adapters."""

from .chat import (
    CHAT_CATALOG_SCHEMA,
    CHAT_JOB_SCHEMA,
    CHAT_OPERATION_SCHEMA,
    LLAMA_CPP_CHAT_ADAPTER,
    ChatGatewayError,
    ChatGatewayProfile,
    ChatProfileCatalog,
    CompiledChatRequest,
    compile_chat_request,
    normalize_chat_completion,
)


from .decision import (
    DECISION_CATALOG_SCHEMA,
    DECISION_JOB_SCHEMA,
    DECISION_OPERATION_SCHEMA,
    DECISION_SCORE_KIND,
    DECISION_SEMANTICS_SCHEMA,
    LLAMA_CPP_SCORE_SEMANTICS,
    LLAMA_CPP_SYSTEM_ONE_ADAPTER,
    CompiledDecisionRequest,
    DecisionGatewayError,
    DecisionGatewayProfile,
    DecisionProfileCatalog,
    DecisionSemanticsIdentity,
    compile_decision_request,
    normalize_decision_response,
    validate_decision_provider_response,
)

from .embedding import (
    EMBEDDING_CATALOG_SCHEMA,
    EMBEDDING_JOB_SCHEMA,
    EMBEDDING_OPERATION_SCHEMA,
    EMBEDDING_SPACE_SCHEMA,
    LLAMA_CPP_EMBEDDING_ADAPTER,
    CompiledEmbeddingRequest,
    EmbeddingGatewayError,
    EmbeddingGatewayProfile,
    EmbeddingProfileCatalog,
    EmbeddingSpaceIdentity,
    compile_embedding_request,
    normalize_embedding_response,
    text_policy_digest,
    validate_embedding_response,
)

__all__ = [
    "CHAT_CATALOG_SCHEMA",
    "CHAT_JOB_SCHEMA",
    "CHAT_OPERATION_SCHEMA",
    "LLAMA_CPP_CHAT_ADAPTER",
    "ChatGatewayError",
    "ChatGatewayProfile",
    "ChatProfileCatalog",
    "CompiledChatRequest",
    "compile_chat_request",
    "normalize_chat_completion",
    "DECISION_CATALOG_SCHEMA",
    "DECISION_JOB_SCHEMA",
    "DECISION_OPERATION_SCHEMA",
    "DECISION_SCORE_KIND",
    "DECISION_SEMANTICS_SCHEMA",
    "LLAMA_CPP_SCORE_SEMANTICS",
    "LLAMA_CPP_SYSTEM_ONE_ADAPTER",
    "CompiledDecisionRequest",
    "DecisionGatewayError",
    "DecisionGatewayProfile",
    "DecisionProfileCatalog",
    "DecisionSemanticsIdentity",
    "compile_decision_request",
    "normalize_decision_response",
    "validate_decision_provider_response",
    "EMBEDDING_CATALOG_SCHEMA",
    "EMBEDDING_JOB_SCHEMA",
    "EMBEDDING_OPERATION_SCHEMA",
    "EMBEDDING_SPACE_SCHEMA",
    "LLAMA_CPP_EMBEDDING_ADAPTER",
    "CompiledEmbeddingRequest",
    "EmbeddingGatewayError",
    "EmbeddingGatewayProfile",
    "EmbeddingProfileCatalog",
    "EmbeddingSpaceIdentity",
    "compile_embedding_request",
    "normalize_embedding_response",
    "text_policy_digest",
    "validate_embedding_response",
]