"""Runtime provider contracts and compatibility planning."""

from .contracts import (
    CompatibilityReason,
    ExecutionDemand,
    GPUTopology,
    ManagedRuntime,
    ModelDemand,
    ModelPreparationPolicy,
    ModelTopology,
    ResidencyPolicy,
    RuntimeCompatibility,
    RuntimeCompatibilityContext,
    RuntimeHealth,
    RuntimeHealthState,
    RuntimeHostFacts,
    RuntimeProvider,
    RuntimeProviderInfo,
    RuntimeSelection,
    RuntimeSelectionMode,
    RuntimeSetupIntent,
)
from .planner import (
    RuntimeCatalog,
    RuntimeResolution,
    RuntimeSelectionError,
    evaluate_catalog,
    evaluate_provider,
    resolve_runtime,
)

__all__ = [
    "CompatibilityReason",
    "ExecutionDemand",
    "GPUTopology",
    "ManagedRuntime",
    "ModelDemand",
    "ModelPreparationPolicy",
    "ModelTopology",
    "ResidencyPolicy",
    "RuntimeCatalog",
    "RuntimeCompatibility",
    "RuntimeCompatibilityContext",
    "RuntimeHealth",
    "RuntimeHealthState",
    "RuntimeHostFacts",
    "RuntimeProvider",
    "RuntimeProviderInfo",
    "RuntimeResolution",
    "RuntimeSelection",
    "RuntimeSelectionError",
    "RuntimeSelectionMode",
    "RuntimeSetupIntent",
    "evaluate_catalog",
    "evaluate_provider",
    "resolve_runtime",
    "RuntimeLifecycleError",
    "RuntimeLifecycleManager",
    "SecretReference",
    "SetupAction",
    "SetupActionKind",
    "SetupActionResult",
    "SetupActionStatus",
    "SetupApplyPolicy",
    "SetupDiscoverySnapshot",
    "SetupEngine",
    "SetupExecutionMode",
    "SetupLayout",
    "SetupPlan",
    "SetupPolicyError",
    "SetupProbe",
    "SetupRunReport",
    "SetupTarget",
    "SetupTargetError",
    "build_setup_plan",
    "discover_local_host_facts",
]

from .discovery import SetupDiscoverySnapshot, discover_local_host_facts
from .lifecycle import RuntimeLifecycleError, RuntimeLifecycleManager
from .setup import (
    SecretReference,
    SetupAction,
    SetupActionKind,
    SetupActionResult,
    SetupActionStatus,
    SetupApplyPolicy,
    SetupEngine,
    SetupExecutionMode,
    SetupLayout,
    SetupPlan,
    SetupPolicyError,
    SetupProbe,
    SetupRunReport,
    SetupTarget,
    SetupTargetError,
    build_setup_plan,
)
