"""Runtime provider contracts and compatibility planning."""

from .contracts import (
    CompatibilityReason,
    ExecutionDemand,
    GPUTopology,
    ManagedRuntime,
    ModelDemand,
    ModelPreparationPolicy,
    ModelTopology,
    ResidencyPolicy,
    RuntimeCompatibility,
    RuntimeCompatibilityContext,
    RuntimeHealth,
    RuntimeHealthState,
    RuntimeHostFacts,
    RuntimeProvider,
    RuntimeProviderInfo,
    RuntimeSelection,
    RuntimeSelectionMode,
    RuntimeSetupIntent,
)
from .deployment import (
    RuntimeDeploymentSpec,
    build_runtime_deployment_spec,
    managed_runtime_from_deployment,
    provider_from_deployment,
)
from .planner import (
    RuntimeCatalog,
    RuntimeResolution,
    RuntimeSelectionError,
    evaluate_catalog,
    evaluate_provider,
    resolve_runtime,
)

__all__ = [
    "CompatibilityReason",
    "ExecutionDemand",
    "GPUTopology",
    "ManagedRuntime",
    "ModelDemand",
    "ModelPreparationPolicy",
    "ModelTopology",
    "ResidencyPolicy",
    "RuntimeCatalog",
    "RuntimeDeploymentSpec",
    "RuntimeCompatibility",
    "RuntimeCompatibilityContext",
    "RuntimeHealth",
    "RuntimeHealthState",
    "RuntimeHostFacts",
    "RuntimeProvider",
    "RuntimeProviderInfo",
    "RuntimeResolution",
    "RuntimeSelection",
    "RuntimeSelectionError",
    "RuntimeSelectionMode",
    "RuntimeSetupIntent",
    "RuntimeLifecycleError",
    "RuntimeLifecycleManager",
    "build_runtime_deployment_spec",
    "evaluate_catalog",
    "evaluate_provider",
    "managed_runtime_from_deployment",
    "provider_from_deployment",
    "resolve_runtime",
]

from .lifecycle import RuntimeLifecycleError, RuntimeLifecycleManager
